[package]
name = "ace-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ace-kernel = { path = "../kernel" }
ace-repository = { path = "../data/repository" }

dotenv = "0.15.0"
